version: '3'

services:

  upload:
    image: ${UPLOAD_IMAGE}
    environment:
      AMQP_HOST: rabbitmq
      S3_HOST: ${S3_HOST}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - "8080:8080"

  imageproc-runner:
    image: ${IMAGEPROC_RUNNER_IMAGE}
    environment:
      AMQP_HOST: rabbitmq
      AMQP_USER: ${RABBITMQ_USER}
      IMAGEPROC_HOST: imageproc
      S3_HOST: ${S3_HOST}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
  
  imageproc:
    image: ${IMAGEPROC_IMAGE}
  
  provenancedb:
    image: ${PROVENANCEDB_IMAGE}
    environment:
      COUCHDB_HOST: couchdb
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_DB: ${COUCHDB_DB}
      AMQP_HOST: rabbitmq

  couchdb:
    image: couchdb:latest
    volumes:
      - couchdb-data:/opt/couchdb/data
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  couchdb-data:
  rabbitmq-data:
